### ISSUE TITLE
Errors for Many Metallicity Values

### ISSUE THREAD

**Issue by johndonor3** [jonathansick/padova#3]
I was really enjoying your package, until I tried to pull many metallicities. I'm using the AgeGridRequest in a loop to pull a number of metallicities (to create local copies, give the server a break), but I'm getting assertion errors, stating many of my values are outside of the range. For example, all the negative values I tried, and now .05 

I'm not sure if this is by design for some reason, but I know the CMD 2.7 site can create tables with these values, and I'd like to have them. 

Cheers,
-John

**Comment by johndonor3** [comment]
Sorry its in z, that's my bad. Great package! 

-John

**Comment by jonathansick** [comment]
Yeah, I need to document this better... someday :)

**Comment by johndonor3** [comment]
Yes please :)
