### ISSUE TITLE
Reading dowloaded file

### ISSUE THREAD

**Issue by rjavila** [jonathansick/padova#4]
Hi. I can get isochrone requests to work, but since I don't want to slam the server I downloaded the data files. I can't seem to get the package to read the downloaded files. How does one do that?

**Comment by jonathansick** [comment]
If you repeat the same request a second time it will just load the downloaded isochrones from a local cache. Is the caching not working for you?

**Comment by rjavila** [comment]
I didn't realize it was storing things like that. That's useful but it would still be nice if I could open files I've downloaded beforehand.

**Comment by jonathansick** [comment]
For sure. :+1: Feel free to fork the code and modify it for your own applications. I'm not actively using or maintaining it anymore.
